apiVersion: syncer.gkelabs.io/v1alpha1
kind: KRMSyncer
metadata:
  name: pull-syncer
  namespace: default
spec:
  mode: pull
  remote:
    clusterConfig:
      kubeConfigSecretRef:
        name: dest-kubeconfig
  rules:
  - group: e2e.gkelabs.io
    version: v1alpha1
    kind: TestCRD
    syncFields:
    - spec
    - status
