apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testcrds.e2e.gkelabs.io
spec:
  group: e2e.gkelabs.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string
                resourceID:
                  type: string
            status:
              type: object
              properties:
                bar:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: testcrds
    singular: testcrd
    kind: TestCRD
    shortNames:
    - tc
