apiVersion: syncer.gkelabs.io/v1alpha1
kind: KRMSyncer
metadata:
  name: suspend-syncer
  namespace: default
spec:
  suspend: true
  mode: push
  remote:
    gkeCluster:
      project: test-project
      location: us-central1
      name: cluster-b
  rules:
  - group: e2e.gkelabs.io
    version: v1alpha1
    kind: TestCRD
