apiVersion: syncer.gkelabs.io/v1alpha1
kind: KRMSyncer
metadata:
  name: pull-syncer
  namespace: default
spec:
  syncMode: push
  remote:
    clusterConfig:
      kubeConfigSecretRef:
        name: remote-kubeconfig
  rules:
  - group: e2e.gkelabs.io
    version: v1alpha1
    kind: TestCRD
